import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {createClient} from '@hey-api/client-fetch';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

createClient({
  baseUrl:'http://localhost:8080',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
