// This file is auto-generated by @hey-api/openapi-ts

export const $CurrentPlaybackSettings = {
    type: 'object',
    properties: {
        playlists_available: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        selected_playlist: {
            type: 'string',
            example: 'night_all.m3u'
        },
        shuffle: {
            type: 'boolean'
        },
        loop: {
            type: 'boolean'
        },
        vlc_path: {
            type: 'string'
        }
    }
} as const;

export const $NewPlaybackSettings = {
    type: 'object',
    properties: {
        selected_playlist: {
            type: 'string',
            example: 'night_all.m3u'
        },
        shuffle: {
            type: 'boolean'
        },
        loop: {
            type: 'boolean'
        },
        vlc_path: {
            type: 'string'
        }
    }
} as const;

export const $SelectPlaylistRequest = {
    type: 'object',
    properties: {
        playlist: {
            type: 'string'
        }
    }
} as const;